In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset_file_path = '../dataset/Gross Profit vs Competitor 0514.xlsx'

df = pd.read_excel(dataset_file_path)

if df is not None:
  print(f"File {dataset_file_path} loaded successfully.")
else:
  print(f"Failed to load file {dataset_file_path}.")

File ../dataset/Gross Profit vs Competitor 0514.xlsx loaded successfully.

In [3]:
df.columns

Index(['Quote ID', 'Product', 'Kw', 'Unit Price', 'Qty', 'Subtotal Price',
       'Gross Margin Rate ', 'Convert to Order (0:Success, 1:Fail)',
       'Energy grant amount', 'Competitor A', 'Competitor B', 'Competitor C'],
      dtype='object')

## Mastiin jawaban narasumber tentang competitor B

In [4]:
compe_b_notnull = df[df['Competitor B'].notna()][['Quote ID', 'Product', 'Kw', 'Competitor B']]
compe_b_notnull.describe()

          Kw  Competitor B
count  466.0         466.0
mean    75.0      900000.0
std      0.0           0.0
min     75.0      900000.0
25%     75.0      900000.0
50%     75.0      900000.0
75%     75.0      900000.0
max     75.0      900000.0

In [5]:
compe_b_notnull.describe(include='object')

       Quote ID Product
count       466     466
unique      443       2
top     Q-14177      N1
freq          3     404

In [6]:
compe_b_notnull['Product'].unique()

array(['N1', 'O1'], dtype=object)

## Feature engineering: known unknown competitor price

In [7]:
df['is_compe_a'] = df['Competitor A'].notna()
df['is_compe_b'] = df['Competitor B'].notna()
df['is_compe_c'] = df['Competitor C'].notna()

df['known_num_compe'] = df[['is_compe_a', 'is_compe_b', 'is_compe_c']].sum(axis=1)
df

,Quote ID,Product,Kw,Unit Price,Qty,Subtotal Price,Gross Margin Rate,"Convert to Order (0:Success, 1:Fail)",Energy grant amount,Competitor A,Competitor B,Competitor C,is_compe_a,is_compe_b,is_compe_c,known_num_compe
0,Q-00114,W,11.0,136000.0,1,136000.0,0.0712,0,66000,NaN,NaN,NaN,False,False,False,0
1,Q-00119,H1,37.0,290000.0,2,580000.0,0.3079,0,222000,360000.0,NaN,NaN,True,False,False,1
2,Q-00161,Y,150.0,2379000.0,1,2379000.0,0.4224,1,720000,NaN,NaN,NaN,False,False,False,0
3,Q-00214,I1,22.0,300000.0,1,300000.0,0.6787,0,132000,240000.0,NaN,NaN,True,False,False,1
4,Q-00517,I1,22.0,228964.0,1,228964.0,0.2949,0,132000,240000.0,NaN,NaN,True,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,Q-44379,H1,37.0,355752.0,1,355752.0,0.3879,0,222000,360000.0,NaN,NaN,True,False,False,1
4990,Q-42582,X,11.0,203000.0,1,203000.0,0.5103,1,66000,NaN,NaN,NaN,False,False,False,0
4991,Q-45260,X,11.0,123911.2,1,123911.2,0.1931,0,66000,NaN,NaN,NaN,False,False,False,0
4992,Q-22566,O1,75.0,626400.0,1,626400.0,0.2627,0,375000,760000.0,900000.0,NaN,True,True,False,2
4993,Q-44825,X,11.0,121800.0,1,121800.0,0.1896,0,66000,NaN,NaN,NaN,False,False,False,0

In [8]:
df['avg_compe_price'] = df['Competitor A'] + df['Competitor B'] + df['Competitor C']
df['avg_compe_price'] = df['avg_compe_price'] / df['known_num_compe']

df['max_compe_price'] = df[['Competitor A', 'Competitor B', 'Competitor C']].max(axis=1)
df['min_compe_price'] = df[['Competitor A', 'Competitor B', 'Competitor C']].min(axis=1)

df

,Quote ID,Product,Kw,Unit Price,Qty,Subtotal Price,Gross Margin Rate,"Convert to Order (0:Success, 1:Fail)",Energy grant amount,Competitor A,Competitor B,Competitor C,is_compe_a,is_compe_b,is_compe_c,known_num_compe,avg_compe_price,max_compe_price,min_compe_price
0,Q-00114,W,11.0,136000.0,1,136000.0,0.0712,0,66000,NaN,NaN,NaN,False,False,False,0,NaN,NaN,NaN
1,Q-00119,H1,37.0,290000.0,2,580000.0,0.3079,0,222000,360000.0,NaN,NaN,True,False,False,1,NaN,360000.0,360000.0
2,Q-00161,Y,150.0,2379000.0,1,2379000.0,0.4224,1,720000,NaN,NaN,NaN,False,False,False,0,NaN,NaN,NaN
3,Q-00214,I1,22.0,300000.0,1,300000.0,0.6787,0,132000,240000.0,NaN,NaN,True,False,False,1,NaN,240000.0,240000.0
4,Q-00517,I1,22.0,228964.0,1,228964.0,0.2949,0,132000,240000.0,NaN,NaN,True,False,False,1,NaN,240000.0,240000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4989,Q-44379,H1,37.0,355752.0,1,355752.0,0.3879,0,222000,360000.0,NaN,NaN,True,False,False,1,NaN,360000.0,360000.0
4990,Q-42582,X,11.0,203000.0,1,203000.0,0.5103,1,66000,NaN,NaN,NaN,False,False,False,0,NaN,NaN,NaN
4991,Q-45260,X,11.0,123911.2,1,123911.2,0.1931,0,66000,NaN,NaN,NaN,False,False,False,0,NaN,NaN,NaN
4992,Q-22566,O1,75.0,626400.0,1,626400.0,0.2627,0,375000,760000.0,900000.0,NaN,True,True,False,2,NaN,900000.0,760000.0
4993,Q-44825,X,11.0,121800.0,1,121800.0,0.1896,0,66000,NaN,NaN,NaN,False,False,False,0,NaN,NaN,NaN

## Impute missing competitor price

### apakah nilai price sama untuk semua kw?

In [9]:
df.columns = df.columns.str.strip()
competitor_cols = ['Competitor A', 'Competitor B', 'Competitor C']

In [10]:
check_competitor_a = (
    df.groupby('Kw')['Competitor A']
      .nunique(dropna=True)
      .reset_index(name='n_unique_competitor_a')
)

check_competitor_a

       Kw  n_unique_competitor_a
0     7.5                      2
1    11.0                      0
2    15.0                      1
3    22.0                      1
4    37.0                      1
5    55.0                      1
6    75.0                      1
7   110.0                      1
8   150.0                      0
9   160.0                      0
10  200.0                      0

In [11]:
check_competitor_b = (
    df.groupby('Kw')['Competitor B']
      .nunique(dropna=True)
      .reset_index(name='n_unique_competitor_b')
)

check_competitor_b

       Kw  n_unique_competitor_b
0     7.5                      0
1    11.0                      0
2    15.0                      0
3    22.0                      0
4    37.0                      0
5    55.0                      0
6    75.0                      1
7   110.0                      0
8   150.0                      0
9   160.0                      0
10  200.0                      0

In [12]:
check_competitor_c = (
    df.groupby('Kw')['Competitor C']
      .nunique(dropna=True)
      .reset_index(name='n_unique_competitor_c')
)

check_competitor_c

       Kw  n_unique_competitor_c
0     7.5                      0
1    11.0                      0
2    15.0                      0
3    22.0                      0
4    37.0                      0
5    55.0                      0
6    75.0                      0
7   110.0                      0
8   150.0                      0
9   160.0                      1
10  200.0                      1

### apakah ada trend nilai kw terhadap harga compe?

In [13]:
summary_by_kw = (
    df.groupby('Kw')
      .agg(
          competitor_a_unique=('Competitor A', lambda x: sorted(x.dropna().unique())),
          competitor_b_unique=('Competitor B', lambda x: sorted(x.dropna().unique())),
          competitor_c_unique=('Competitor C', lambda x: sorted(x.dropna().unique())),

          competitor_a_avg=('Competitor A', lambda x: x.dropna().mean()),
          competitor_b_avg=('Competitor B', lambda x: x.dropna().mean()),
          competitor_c_avg=('Competitor C', lambda x: x.dropna().mean()),

          n_competitor_a=('Competitor A', lambda x: x.dropna().nunique()),
          n_competitor_b=('Competitor B', lambda x: x.dropna().nunique()),
          n_competitor_c=('Competitor C', lambda x: x.dropna().nunique()),
      )
      .reset_index()
      .sort_values('Kw')
)

summary_by_kw

,Kw,competitor_a_unique,competitor_b_unique,competitor_c_unique,competitor_a_avg,competitor_b_avg,competitor_c_avg,n_competitor_a,n_competitor_b,n_competitor_c
0,7.5,"[10500.0, 130000.0]",[],[],1.225916e+05,NaN,NaN,2,0,0
1,11.0,[],[],[],NaN,NaN,NaN,0,0,0
2,15.0,[170000.0],[],[],1.700000e+05,NaN,NaN,1,0,0
3,22.0,[240000.0],[],[],2.400000e+05,NaN,NaN,1,0,0
4,37.0,[360000.0],[],[],3.600000e+05,NaN,NaN,1,0,0
5,55.0,[620000.0],[],[],6.200000e+05,NaN,NaN,1,0,0
6,75.0,[760000.0],[900000.0],[],7.600000e+05,900000.0,NaN,1,1,0
7,110.0,[1880000.0],[],[],1.880000e+06,NaN,NaN,1,0,0
8,150.0,[],[],[],NaN,NaN,NaN,0,0,0
9,160.0,[],[],[2100000.0],NaN,NaN,2100000.0,0,0,1
10,200.0,[],[],[2000000.0],NaN,NaN,2000000.0,0,0,1

In [14]:
summary_by_kw['competitor_a_avg_is_increasing'] = summary_by_kw['competitor_a_avg'].is_monotonic_increasing
summary_by_kw['competitor_b_avg_is_increasing'] = summary_by_kw['competitor_b_avg'].is_monotonic_increasing
summary_by_kw['competitor_c_avg_is_increasing'] = summary_by_kw['competitor_c_avg'].is_monotonic_increasing

summary_by_kw

,Kw,competitor_a_unique,competitor_b_unique,competitor_c_unique,competitor_a_avg,competitor_b_avg,competitor_c_avg,n_competitor_a,n_competitor_b,n_competitor_c,competitor_a_avg_is_increasing,competitor_b_avg_is_increasing,competitor_c_avg_is_increasing
0,7.5,"[10500.0, 130000.0]",[],[],1.225916e+05,NaN,NaN,2,0,0,False,False,False
1,11.0,[],[],[],NaN,NaN,NaN,0,0,0,False,False,False
2,15.0,[170000.0],[],[],1.700000e+05,NaN,NaN,1,0,0,False,False,False
3,22.0,[240000.0],[],[],2.400000e+05,NaN,NaN,1,0,0,False,False,False
4,37.0,[360000.0],[],[],3.600000e+05,NaN,NaN,1,0,0,False,False,False
5,55.0,[620000.0],[],[],6.200000e+05,NaN,NaN,1,0,0,False,False,False
6,75.0,[760000.0],[900000.0],[],7.600000e+05,900000.0,NaN,1,1,0,False,False,False
7,110.0,[1880000.0],[],[],1.880000e+06,NaN,NaN,1,0,0,False,False,False
8,150.0,[],[],[],NaN,NaN,NaN,0,0,0,False,False,False
9,160.0,[],[],[2100000.0],NaN,NaN,2100000.0,0,0,1,False,False,False
10,200.0,[],[],[2000000.0],NaN,NaN,2000000.0,0,0,1,False,False,False

In [15]:
for col in ['Competitor A', 'Competitor B', 'Competitor C']:
    print(f'\n=== {col} ===')

    result = (
        df.dropna(subset=[col])
          .groupby(['Kw', col, 'Product'], dropna=False)
          .size()
          .reset_index(name='count')
          .sort_values(['Kw', col, 'Product'])
    )

    display(result)

=== Competitor A ===

       Kw  Competitor A Product  count
0     7.5       10500.0       A     23
1     7.5      130000.0       Q    339
2     7.5      130000.0       R      9
3    15.0      170000.0      A1    360
4    22.0      240000.0      I1   1532
5    37.0      360000.0      H1   1209
6    55.0      620000.0      J1     73
7    55.0      620000.0      K1      3
8    55.0      620000.0      L1      4
9    55.0      620000.0      M1      6
10   75.0      760000.0      N1    404
11   75.0      760000.0      O1     62
12  110.0     1880000.0       S     47
13  110.0     1880000.0       T     13
14  110.0     1880000.0       U     16
15  110.0     1880000.0       V      6

=== Competitor B ===

     Kw  Competitor B Product  count
0  75.0      900000.0      N1    404
1  75.0      900000.0      O1     62

=== Competitor C ===

      Kw  Competitor C Product  count
0  160.0     2100000.0      C1      5
1  200.0     2000000.0      D1     28
2  200.0     2000000.0      E1     17
3  200.0     2000000.0      F1      6
4  200.0     2000000.0      G1      1

In [16]:
for col in competitor_cols:
    print(f'\n=== Check consistency for {col} by Product + Kw ===')

    check_product_kw = (
        df.dropna(subset=[col])
          .groupby(['Product', 'Kw'])[col]
          .agg(
              unique_values=lambda x: sorted(x.unique()),
              n_unique='nunique',
              count='count'
          )
          .reset_index()
          .sort_values(['Kw', 'Product'])
    )

    display(check_product_kw)

=== Check consistency for Competitor A by Product + Kw ===

   Product     Kw unique_values  n_unique  count
0        A    7.5     [10500.0]         1     23
10       Q    7.5    [130000.0]         1    339
11       R    7.5    [130000.0]         1      9
1       A1   15.0    [170000.0]         1    360
3       I1   22.0    [240000.0]         1   1532
2       H1   37.0    [360000.0]         1   1209
4       J1   55.0    [620000.0]         1     73
5       K1   55.0    [620000.0]         1      3
6       L1   55.0    [620000.0]         1      4
7       M1   55.0    [620000.0]         1      6
8       N1   75.0    [760000.0]         1    404
9       O1   75.0    [760000.0]         1     62
12       S  110.0   [1880000.0]         1     47
13       T  110.0   [1880000.0]         1     13
14       U  110.0   [1880000.0]         1     16
15       V  110.0   [1880000.0]         1      6

=== Check consistency for Competitor B by Product + Kw ===

  Product    Kw unique_values  n_unique  count
0      N1  75.0    [900000.0]         1    404
1      O1  75.0    [900000.0]         1     62

=== Check consistency for Competitor C by Product + Kw ===

  Product     Kw unique_values  n_unique  count
0      C1  160.0   [2100000.0]         1      5
1      D1  200.0   [2000000.0]         1     28
2      E1  200.0   [2000000.0]         1     17
3      F1  200.0   [2000000.0]         1      6
4      G1  200.0   [2000000.0]         1      1

In [17]:
for col in competitor_cols:
    print(f'\n=== Imputation opportunity for {col} ===')

    temp = df.copy()

    # jumlah nilai non-null per Product + Kw
    temp[f'{col}_known_count'] = (
        temp.groupby(['Product', 'Kw'])[col]
            .transform(lambda x: x.notna().sum())
    )

    # jumlah unique non-null per Product + Kw
    temp[f'{col}_n_unique_known'] = (
        temp.groupby(['Product', 'Kw'])[col]
            .transform(lambda x: x.dropna().nunique())
    )

    opportunity = temp[
        temp[col].isna() &
        (temp[f'{col}_known_count'] > 0) &
        (temp[f'{col}_n_unique_known'] == 1)
    ][
        ['Quote ID', 'Product', 'Kw', col, f'{col}_known_count', f'{col}_n_unique_known']
    ]

    display(opportunity)

=== Imputation opportunity for Competitor A ===

Empty DataFrame
Columns: [Quote ID, Product, Kw, Competitor A, Competitor A_known_count, Competitor A_n_unique_known]
Index: []

=== Imputation opportunity for Competitor B ===

Empty DataFrame
Columns: [Quote ID, Product, Kw, Competitor B, Competitor B_known_count, Competitor B_n_unique_known]
Index: []

=== Imputation opportunity for Competitor C ===

Empty DataFrame
Columns: [Quote ID, Product, Kw, Competitor C, Competitor C_known_count, Competitor C_n_unique_known]
Index: []

In [18]:
for col in competitor_cols:
    print(f'\n=== {col}: consistency by Product ===')

    product_comp_check = (
        df.dropna(subset=[col])
          .groupby('Product')
          .agg(
              kw_unique=('Kw', lambda x: sorted(x.dropna().unique())),
              competitor_unique=(col, lambda x: sorted(x.dropna().unique())),
              n_unique_price=(col, lambda x: x.dropna().nunique()),
              count=(col, 'count')
          )
          .reset_index()
          .sort_values('Product')
    )

    display(product_comp_check)

=== Competitor A: consistency by Product ===

   Product kw_unique competitor_unique  n_unique_price  count
0        A     [7.5]         [10500.0]               1     23
1       A1    [15.0]        [170000.0]               1    360
2       H1    [37.0]        [360000.0]               1   1209
3       I1    [22.0]        [240000.0]               1   1532
4       J1    [55.0]        [620000.0]               1     73
5       K1    [55.0]        [620000.0]               1      3
6       L1    [55.0]        [620000.0]               1      4
7       M1    [55.0]        [620000.0]               1      6
8       N1    [75.0]        [760000.0]               1    404
9       O1    [75.0]        [760000.0]               1     62
10       Q     [7.5]        [130000.0]               1    339
11       R     [7.5]        [130000.0]               1      9
12       S   [110.0]       [1880000.0]               1     47
13       T   [110.0]       [1880000.0]               1     13
14       U   [110.0]       [1880000.0]               1     16
15       V   [110.0]       [1880000.0]               1      6

=== Competitor B: consistency by Product ===

  Product kw_unique competitor_unique  n_unique_price  count
0      N1    [75.0]        [900000.0]               1    404
1      O1    [75.0]        [900000.0]               1     62

=== Competitor C: consistency by Product ===

  Product kw_unique competitor_unique  n_unique_price  count
0      C1   [160.0]       [2100000.0]               1      5
1      D1   [200.0]       [2000000.0]               1     28
2      E1   [200.0]       [2000000.0]               1     17
3      F1   [200.0]       [2000000.0]               1      6
4      G1   [200.0]       [2000000.0]               1      1

In [19]:
for col in competitor_cols:
    print(f'\n=== Missing check for known-product {col} ===')

    # Product yang punya harga competitor untuk kolom tersebut
    known_products = df.loc[df[col].notna(), 'Product'].unique()

    # Row dengan product tersebut, tapi competitor price masih kosong
    missing_known_product = df[
        df['Product'].isin(known_products) &
        df[col].isna()
    ][
        ['Quote ID', 'Product', 'Kw', 'Unit Price', 'Qty', 'Subtotal Price',
         'Competitor A', 'Competitor B', 'Competitor C']
    ].sort_values(['Product', 'Kw', 'Quote ID'])

    print(f'Number of rows that can potentially be imputed by Product: {len(missing_known_product)}')
    display(missing_known_product)

=== Missing check for known-product Competitor A ===
Number of rows that can potentially be imputed by Product: 0

Empty DataFrame
Columns: [Quote ID, Product, Kw, Unit Price, Qty, Subtotal Price, Competitor A, Competitor B, Competitor C]
Index: []

=== Missing check for known-product Competitor B ===
Number of rows that can potentially be imputed by Product: 0

Empty DataFrame
Columns: [Quote ID, Product, Kw, Unit Price, Qty, Subtotal Price, Competitor A, Competitor B, Competitor C]
Index: []

=== Missing check for known-product Competitor C ===
Number of rows that can potentially be imputed by Product: 0

Empty DataFrame
Columns: [Quote ID, Product, Kw, Unit Price, Qty, Subtotal Price, Competitor A, Competitor B, Competitor C]
Index: []

## Drop rows Qty <= 0

In [20]:
print(f"Shape before: {df.shape}")
df = df[df['Qty'] > 0]
print(f"Shape after: {df.shape}")

Shape before: (4994, 19)
Shape after: (4991, 19)

## Deduplication

In [21]:
print(f"Size before drop exact duplicates: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"Size after drop exact duplicates: {df.shape}")

Size before drop exact duplicates: (4991, 19)
Size after drop exact duplicates: (4902, 19)

C:\Users\surya\AppData\Local\Temp\ipykernel_31140\1549169914.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

## Apakah untuk energy grant itu basisnya terhadap product atau Quote ID?

In [22]:
df.columns

Index(['Quote ID', 'Product', 'Kw', 'Unit Price', 'Qty', 'Subtotal Price',
       'Gross Margin Rate', 'Convert to Order (0:Success, 1:Fail)',
       'Energy grant amount', 'Competitor A', 'Competitor B', 'Competitor C',
       'is_compe_a', 'is_compe_b', 'is_compe_c', 'known_num_compe',
       'avg_compe_price', 'max_compe_price', 'min_compe_price'],
      dtype='object')

In [23]:
grant_by_quote = (
    df.groupby('Quote ID')["Energy grant amount"]
      .agg(
          grant_unique=lambda x: sorted(x.dropna().unique()),
          n_unique_grant=lambda x: x.dropna().nunique(),
          n_rows='count'
      )
      .reset_index()
      .sort_values('Quote ID')
)

grant_by_quote

     Quote ID      grant_unique  n_unique_grant  n_rows
0     Q-00114           [66000]               1       1
1     Q-00119          [222000]               1       1
2     Q-00161          [720000]               1       1
3     Q-00167          [375000]               1       1
4     Q-00214          [132000]               1       1
...       ...               ...             ...     ...
4635  Q-45794           [45000]               1       1
4636  Q-45799          [222000]               1       1
4637  Q-45803          [528000]               1       1
4638  Q-45808  [451000, 528000]               2       2
4639  Q-45815          [132000]               1       1

[4640 rows x 4 columns]

In [24]:
grant_by_quote[grant_by_quote['n_unique_grant'] > 1]

     Quote ID      grant_unique  n_unique_grant  n_rows
8     Q-00525  [132000, 222000]               2       2
23    Q-02428  [322500, 528000]               2       4
40    Q-03631  [222000, 375000]               2       3
92    Q-05821  [113520, 132000]               2       2
99    Q-05850  [132000, 222000]               2       2
...       ...               ...             ...     ...
4540  Q-44771  [132000, 375000]               2       2
4574  Q-45069  [222000, 375000]               2       2
4593  Q-45294  [181500, 375000]               2       2
4626  Q-45710   [38700, 236500]               2       2
4638  Q-45808  [451000, 528000]               2       2

[115 rows x 4 columns]

In [25]:
grant_by_product = (
    df.groupby('Product')
      .agg(
          kw_unique=('Kw', lambda x: sorted(x.dropna().unique())),
          grant_unique=('Energy grant amount', lambda x: sorted(x.dropna().unique())),
          n_unique_grant=('Energy grant amount', lambda x: x.dropna().nunique()),
          n_rows=('Quote ID', 'count')
      )
      .reset_index()
      .sort_values('Product')
)

grant_by_product

   Product kw_unique grant_unique  n_unique_grant  n_rows
0        A     [7.5]      [38700]               1      23
1       A1    [15.0]      [90000]               1     360
2        B    [11.0]      [56760]               1       9
3       B1   [160.0]     [768000]               1       1
4        C   [110.0]     [451000]               1      10
5       C1   [160.0]     [768000]               1       5
6        D   [110.0]     [451000]               1       9
7       D1   [200.0]     [960000]               1      28
8        E    [15.0]      [48600]               1       4
9       E1   [200.0]     [960000]               1      17
10       F   [150.0]     [615000]               1       3
11      F1   [200.0]     [960000]               1       6
12       G   [150.0]     [615000]               1       7
13      G1   [200.0]     [960000]               1       1
14       H   [200.0]     [820000]               1       1
15      H1    [37.0]     [222000]               1    1173
16       I   [200.0]     [820000]               1       7
17      I1    [22.0]     [132000]               1    1501
18       J    [22.0]     [113520]               1       9
19      J1    [55.0]     [181500]               1      73
20       K    [37.0]     [190920]               1      17
21      K1    [55.0]     [181500]               1       3
22       L    [55.0]     [236500]               1       1
23      L1    [55.0]     [181500]               1       4
24       M    [75.0]     [322500]               1       9
25      M1    [55.0]     [181500]               1       5
26       N    [75.0]     [322500]               1      10
27      N1    [75.0]     [375000]               1     397
28       O    [75.0]     [322500]               1      13
29      O1    [75.0]     [375000]               1      62
30       P    [75.0]     [322500]               1       3
31      P1    [75.0]     [247500]               1      18
32       Q     [7.5]      [45000]               1     339
33      Q1    [75.0]     [247500]               1      10
34       R     [7.5]      [45000]               1       9
35       S   [110.0]     [528000]               1      47
36       T   [110.0]     [528000]               1      12
37       U   [110.0]     [528000]               1      15
38       V   [110.0]     [528000]               1       5
39       W    [11.0]      [66000]               1     644
40       X    [11.0]      [66000]               1      12
41       Y   [150.0]     [720000]               1      11
42       Z   [150.0]     [720000]               1       9

In [26]:
grant_by_product[grant_by_product['n_unique_grant'] > 1]

Empty DataFrame
Columns: [Product, kw_unique, grant_unique, n_unique_grant, n_rows]
Index: []

## Feature Engineering: ordering same Quote ID, same Product but different price

---

based on our 1st interview we know that we need to treat the highest unit price as the final price

### cek dulu deh apa bakrangkali kw nya beda ya

---

Jawab: tidak ada ya, semua kw sama

In [27]:
quote_product_kw_check = (
    df.groupby(['Quote ID', 'Product'])
      .agg(
          kw_unique=('Kw', lambda x: sorted(x.dropna().unique())),
          n_unique_kw=('Kw', lambda x: x.dropna().nunique()),
          unit_price_unique=('Unit Price', lambda x: sorted(x.dropna().unique())),
          n_unique_unit_price=('Unit Price', lambda x: x.dropna().nunique()),
          n_rows=('Quote ID', 'count')
      )
      .reset_index()
      .sort_values(['Quote ID', 'Product'])
)

quote_product_kw_check

,Quote ID,Product,kw_unique,n_unique_kw,unit_price_unique,n_unique_unit_price,n_rows
0,Q-00114,W,[11.0],1,[136000.0],1,1
1,Q-00119,H1,[37.0],1,[290000.0],1,1
2,Q-00161,Y,[150.0],1,[2379000.0],1,1
3,Q-00167,O1,[75.0],1,[775970.0],1,1
4,Q-00214,I1,[22.0],1,[300000.0],1,1
...,...,...,...,...,...,...,...
4759,Q-45799,H1,[37.0],1,[373248.0],1,1
4760,Q-45803,T,[110.0],1,[1590300.0],1,1
4761,Q-45808,C,[110.0],1,[1100000.0],1,1
4762,Q-45808,U,[110.0],1,[1500000.0],1,1
4763,Q-45815,I1,[22.0],1,[273780.0],1,1

In [28]:
quote_product_different_kw = quote_product_kw_check[
    quote_product_kw_check['n_unique_kw'] > 1
]

quote_product_different_kw

Empty DataFrame
Columns: [Quote ID, Product, kw_unique, n_unique_kw, unit_price_unique, n_unique_unit_price, n_rows]
Index: []

### oke gas oke gas buat fiturnya

In [29]:
df_fe = (
    df.sort_values(['Quote ID', 'Product', 'Unit Price'])
      .assign(
          price_order=lambda x: x.groupby(['Quote ID', 'Product']).cumcount() + 1,
          is_highest_price=lambda x: (
              x['Unit Price'] == x.groupby(['Quote ID', 'Product'])['Unit Price'].transform('max')
          ).astype(int)
      )
)

same_quote_product = df_fe[
    df_fe.groupby(['Quote ID', 'Product'])['Quote ID']
         .transform('count') > 1
]

same_quote_product[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

,Quote ID,Product,Kw,Unit Price,price_order,is_highest_price,"Convert to Order (0:Success, 1:Fail)"
21,Q-01366,N1,75.0,683400.0,1,0,0
13,Q-01366,N1,75.0,845960.0,2,1,0
60,Q-02428,O,75.0,614000.0,1,0,0
26,Q-02428,O,75.0,659000.0,2,1,0
59,Q-02428,S,110.0,1084000.0,1,0,0
...,...,...,...,...,...,...,...
4875,Q-44580,R,7.5,98644.0,2,1,0
4876,Q-44580,X,11.0,118531.7,1,1,0
4877,Q-44580,X,11.0,118531.7,2,1,0
4924,Q-45260,X,11.0,123424.0,1,0,0
4991,Q-45260,X,11.0,123911.2,2,1,0

In [30]:
same_quote_product = df_fe[
    df_fe.groupby(['Quote ID', 'Product'])['Quote ID']
         .transform('count') > 1
].copy()

#### success all

In [31]:
success_all = same_quote_product[
    same_quote_product.groupby(['Quote ID', 'Product'])['Convert to Order (0:Success, 1:Fail)']
        .transform(lambda x: (x == 0).all())
].copy()

print(f"Number of rows that success all: {len(success_all)}")

success_all[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

Number of rows that success all: 229

,Quote ID,Product,Kw,Unit Price,price_order,is_highest_price,"Convert to Order (0:Success, 1:Fail)"
21,Q-01366,N1,75.0,683400.0,1,0,0
13,Q-01366,N1,75.0,845960.0,2,1,0
60,Q-02428,O,75.0,614000.0,1,0,0
26,Q-02428,O,75.0,659000.0,2,1,0
59,Q-02428,S,110.0,1084000.0,1,0,0
...,...,...,...,...,...,...,...
4875,Q-44580,R,7.5,98644.0,2,1,0
4876,Q-44580,X,11.0,118531.7,1,1,0
4877,Q-44580,X,11.0,118531.7,2,1,0
4924,Q-45260,X,11.0,123424.0,1,0,0
4991,Q-45260,X,11.0,123911.2,2,1,0

In [32]:
# SAME UNIT PRICE: ini apa ditanyain ya, apakah ada kemungkinan dalam 1 quote id terdapat beberapa product id sama dan harga yang sama
success_all_same_price = success_all[
    success_all.groupby(['Quote ID', 'Product'])['Unit Price']
        .transform('nunique') == 1
].copy()

success_all_same_price[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

,Quote ID,Product,Kw,Unit Price,price_order,is_highest_price,"Convert to Order (0:Success, 1:Fail)"
660,Q-10273,H1,37.0,350000.0,1,1,0
661,Q-10273,H1,37.0,350000.0,2,1,0
811,Q-11298,I1,22.0,180039.6,1,1,0
812,Q-11298,I1,22.0,180039.6,2,1,0
865,Q-11375,I1,22.0,187012.8,1,1,0
...,...,...,...,...,...,...,...
4627,Q-41747,I1,22.0,269568.0,2,1,0
4874,Q-44580,R,7.5,98644.0,1,1,0
4875,Q-44580,R,7.5,98644.0,2,1,0
4876,Q-44580,X,11.0,118531.7,1,1,0
4877,Q-44580,X,11.0,118531.7,2,1,0

In [33]:
df.loc[[20, 54, 334, 1405]]

KeyError: '[54, 1405] not in index'

In [ ]:
# DIFFERENT UNIT PRICE: ambil highest price sebagai harga menangnya
success_all_diff_price = success_all[
    success_all.groupby(['Quote ID', 'Product'])['Unit Price']
        .transform('nunique') > 1
].copy()

success_all_diff_price[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

,Quote ID,Product,Kw,Unit Price,price_order,is_highest_price,"Convert to Order (0:Success, 1:Fail)"
21,Q-01366,N1,75.0,683400.0,1,0,0
13,Q-01366,N1,75.0,845960.0,2,1,0
60,Q-02428,O,75.0,614000.0,1,0,0
26,Q-02428,O,75.0,659000.0,2,1,0
59,Q-02428,S,110.0,1084000.0,1,0,0
...,...,...,...,...,...,...,...
4589,Q-41659,I1,22.0,256932.0,2,1,0
4964,Q-43688,N1,75.0,554000.0,1,0,0
4766,Q-43688,N1,75.0,605000.0,2,1,0
4924,Q-45260,X,11.0,123424.0,1,0,0
4991,Q-45260,X,11.0,123911.2,2,1,0

#### fail all

In [ ]:
fail_all = same_quote_product[
    same_quote_product.groupby(['Quote ID', 'Product'])['Convert to Order (0:Success, 1:Fail)']
        .transform(lambda x: (x == 1).all())
].copy()

print(f"Number of rows that fail all: {len(fail_all)}")

fail_all[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

Number of rows that fail all: 34

,Quote ID,Product,Kw,Unit Price,price_order,is_highest_price,"Convert to Order (0:Success, 1:Fail)"
33,Q-03409,N1,75.0,1283500.0,1,1,1
34,Q-03409,N1,75.0,1283500.0,2,1,1
79,Q-05577,E,15.0,408100.0,1,1,1
80,Q-05577,E,15.0,408100.0,2,1,1
111,Q-05854,W,11.0,173420.0,1,0,1
112,Q-05854,W,11.0,173420.0,2,0,1
113,Q-05854,W,11.0,290000.0,3,1,1
131,Q-05939,I1,22.0,264420.0,1,1,1
132,Q-05939,I1,22.0,264420.0,2,1,1
2529,Q-08241,D,110.0,1205838.0,1,1,1
2531,Q-08241,D,110.0,1205838.0,2,1,1
2532,Q-08241,D,110.0,1205838.0,3,1,1
2530,Q-08241,T,110.0,1431270.0,1,1,1
2533,Q-08241,T,110.0,1431270.0,2,1,1
775,Q-11167,W,11.0,176030.0,1,0,1
786,Q-11167,W,11.0,290000.0,2,1,1
1084,Q-13025,I1,22.0,282672.0,1,1,1
1085,Q-13025,I1,22.0,282672.0,2,1,1
1664,Q-16226,I1,22.0,265356.0,1,0,1
1666,Q-16226,I1,22.0,421200.0,2,1,1
1693,Q-16415,W,11.0,188500.0,1,1,1
2837,Q-16415,W,11.0,188500.0,2,1,1
2538,Q-21643,W,11.0,182700.0,1,1,1
2539,Q-21643,W,11.0,182700.0,2,1,1
2540,Q-21643,W,11.0,182700.0,3,1,1
2541,Q-21643,W,11.0,182700.0,4,1,1
3936,Q-33495,H1,37.0,355752.0,1,0,1
3944,Q-33495,H1,37.0,583200.0,2,1,1
4258,Q-37704,H1,37.0,379080.0,1,1,1
4259,Q-37704,H1,37.0,379080.0,2,1,1
4296,Q-38229,M1,55.0,991424.0,1,1,1
4297,Q-38229,M1,55.0,991424.0,2,1,1
4918,Q-45103,N1,75.0,690000.0,1,1,1
4971,Q-45103,N1,75.0,690000.0,2,1,1

#### mixu

In [ ]:
mixed_success_fail = same_quote_product[
    same_quote_product.groupby(['Quote ID', 'Product'])['Convert to Order (0:Success, 1:Fail)']
        .transform(lambda x: x.nunique() > 1)
].copy()

print(f"Number of rows that mixed success and fail: {len(mixed_success_fail)}")

mixed_success_fail[
    ['Quote ID', 'Product', 'Kw', 'Unit Price',
     'price_order', 'is_highest_price',
     'Convert to Order (0:Success, 1:Fail)']
].sort_values(['Quote ID', 'Product', 'price_order'])

Number of rows that mixed success and fail: 0

Empty DataFrame
Columns: [Quote ID, Product, Kw, Unit Price, price_order, is_highest_price, Convert to Order (0:Success, 1:Fail)]
Index: []

## Feature enginerering: perhitungan

In [ ]:
df_fe['min_competitor_price'] = df_fe[competitor_cols].min(axis=1, skipna=True)

df_fe['price_gap_vs_min_competitor'] = (
    df_fe['Unit Price'] - df_fe['min_competitor_price']
)

df_fe['price_ratio_vs_min_competitor'] = (
    df_fe['Unit Price'] / df_fe['min_competitor_price']
)

In [ ]:
df_fe['has_energy_grant'] = df_fe['Energy grant amount'].notna().astype(int)

df_fe['effective_price_after_grant'] = (
    df_fe['Subtotal Price'] - df_fe['Energy grant amount']
)

df_fe['grant_ratio_to_subtotal'] = (
    df_fe['Energy grant amount'] / df_fe['Subtotal Price']
)

In [ ]:
df_fe['estimated_cost'] = (
    df_fe['Subtotal Price'] * (1 - df_fe['Gross Margin Rate'])
)

df_fe['estimated_gross_profit'] = (
    df_fe['Subtotal Price'] - df_fe['estimated_cost']
)

## save data frame

In [ ]:
df_fe.to_csv('../output/df_fe.csv', index=False)

In [ ]:
df_fe.columns

Index(['Quote ID', 'Product', 'Kw', 'Unit Price', 'Qty', 'Subtotal Price',
       'Gross Margin Rate', 'Convert to Order (0:Success, 1:Fail)',
       'Energy grant amount', 'Competitor A', 'Competitor B', 'Competitor C',
       'is_compe_a', 'is_compe_b', 'is_compe_c', 'known_num_compe',
       'avg_compe_price', 'max_compe_price', 'min_compe_price', 'price_order',
       'is_highest_price', 'min_competitor_price',
       'price_gap_vs_min_competitor', 'price_ratio_vs_min_competitor',
       'has_energy_grant', 'effective_price_after_grant',
       'grant_ratio_to_subtotal', 'estimated_cost', 'estimated_gross_profit'],
      dtype='object')